### ISSUE TITLE
Can't send emails

### ISSUE THREAD

**Issue by benbangli78** [BiZken/PhishMailer#11]
I always got this error..

Traceback (most recent call last):                                                                                                                     
  File "PhishMailer.py", line 142, in <module>                                                                                                         
    NormalEmail()                                                                                                                                      
  File "/home/benbangli/PhishMailer/Core/mailer.py", line 32, in NormalEmail                                                                           
    YahooEmail()                                                                                                                                       
  File "/home/benbangli/PhishMailer/Core/Mailer/yahoo.py", line 47, in YahooEmail                                                                      
    server.login(fromaddr, password)                                                                                                                   
  File "/usr/lib/python3.8/smtplib.py", line 723, in login                                                                                             
    (code, resp) = self.auth(                                                                                                                          
  File "/usr/lib/python3.8/smtplib.py", line 635, in auth                                                                                              
    (code, resp) = self.docmd("AUTH", mechanism + " " + response)                                                                                      
  File "/usr/lib/python3.8/smtplib.py", line 425, in docmd                                                                                             
    return self.getreply()                                                                                                                             
  File "/usr/lib/python3.8/smtplib.py", line 398, in getreply                                                                                          
    raise SMTPServerDisconnected("Connection unexpectedly closed")                                                                                     
smtplib.SMTPServerDisconnected: Connection unexpectedly closed

**Comment by BiZken** [comment]
Have you turned on "allow less-secure apps"?

**Comment by benbangli78** [comment]
> 
> 
> Have you turned on "allow less-secure apps"?

Yes it's turned on

**Comment by BiZken** [comment]
If everything goes planned I will drop a new update in the next upcoming days and I will see if I can fix it in that update, I think it can be the port number to yahoo. 
I will check it when I get home and see if that's the problem

**Comment by benbangli78** [comment]
> 
> 
> If everything goes planned I will drop a new update in the next upcoming days and I will see if I can fix it in that update, I think it can be the port number to yahoo.
> I will check it when I get home and see if that's the problem

Thank you

**Comment by BiZken** [comment]
I have not updated the whole phishmailer tool but I did change a bit in the Yahoo mailer section of the code, you can see if it works now if you reinstall phishmailer or just change the code in the existing file you already have. 
I also read on these two sites about 2FA for yahoo but I think I Might have fixed it, sadly I don't have a yahoo email so I can try so you can be my "test subject" this time
Tell Me If it worked or not: 
https://stackoverflow.com/questions/40904957/send-email-using-my-yahoo-account-error-message

https://help.yahoo.com/kb/SLN4724.html?guccounter=1&guce_referrer=aHR0cHM6Ly9qdWxpZW5oYXJidWxvdC5jb20vcHl0aG9uLWVtYWlscy5odG1s&guce_referrer_sig=AQAAAHbzPt109HlET-3zzEaTI97jceUAXg-58DLPtiDCbR2bBD_t0AadzhI_nYZ6SinltmcrKRnxZE6sJVopBumaHP3W_P1KBDeDSAyezkGlvZib4NGaIczkc3Lb-PP-9sfIrBHBJ-VUFH-WO3GtiaP30DDmVlqsgxGyqCR8W-p5m4Paimport
